package ru.icerow.zanti;

import java.awt.GridLayout;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import ru.icerow.zanti.db.ZantiDao;

/**
 *
 * @author Artyom
 */
public class DocumentProgressUI extends javax.swing.JFrame {
    private ZantiDao dao;
    List<DocumentStage> stages;
    List<JPanel> panels;
    List<DocumentStageContent>[] stageContent;
    List<JCheckBox>[] panelCheckBoxes;
    int stageIds[];
    
    /**
     * Creates new form DocumentProgressUI
     */
    public DocumentProgressUI() {
        initComponents();
        
        dao = DocumentsListUI.dao;
        
//        JPanel panel = new JPanel();
//        jTabbedPane1.addTab("Test", panel);
//        JCheckBox checkbox = new JCheckBox("<html> asldjfl asdfjk haskdjfh akjsdh fk jhaskdjfh kjasdkfj aksjdfjhasdkjfhaksjdf alksdjlkasdklfasldk falsd lfalskdflk askld flkasdlkf alsdf lasdfklalsdjfklasdlfaslkdjfas  d d d d ");
//        JCheckBox checkbox2 = new JCheckBox("test");
//        JCheckBox checkbox3 = new JCheckBox("test");
//        JCheckBox checkbox4 = new JCheckBox("test");
//        checkbox.setLocation(0, 0);
//        int d = 2+2;
//        panel.setLayout(new GridLayout(d, 1));
//        panel.add(checkbox);
//        panel.add(checkbox2);
//        panel.add(checkbox3);
//        panel.add(checkbox4);
        getStages();
        panelCheckBoxes = (List<JCheckBox>[]) Array.newInstance(List.class, stages.size());
        stageContent = (List<DocumentStageContent>[]) Array.newInstance(List.class, stages.size());
        panels = new ArrayList<>();
        stageIds = new int[stages.size()];
        for (DocumentStage stage : stages) {
            JPanel panel = new JPanel();
            panels.add(panel);
            int tabNumber = panels.size()-1;
            int stageId = stage.getId();
            stageIds[tabNumber] = stageId;
            jTabbedPane1.addTab(stage.getName(), panel);
            stageContent[tabNumber] = dao.getStageContent(stageId);
            panelCheckBoxes[tabNumber] = new ArrayList<>();
            panel.setLayout(new GridLayout(stageContent[tabNumber].size(), 1));
            for (DocumentStageContent content : stageContent[tabNumber]) {
                JCheckBox checkBox = new JCheckBox("<html>" + content.getName() + "</html>");
                panelCheckBoxes[tabNumber].add(checkBox);
                panel.add(checkBox);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Прогресс разработки НИР");
        setPreferredSize(new java.awt.Dimension(650, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentProgressUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentProgressUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentProgressUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentProgressUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DocumentProgressUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void getStages() {
        stages = dao.getStages();
    }
}
