package ru.icerow.zanti;

import java.awt.GridLayout;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import ru.icerow.zanti.db.ZantiDao;

/**
 *
 * @author Artyom
 */
public class DocumentProgressUI extends javax.swing.JFrame {
    private ZantiDao dao;
    private List<DocumentStage> stages;
    private List<JPanel> panels;
    private List<DocumentStageContent>[] stageContent;
    private List<JCheckBox>[] panelCheckBoxes;
    private Set<Integer> documentProgress;
    private int stageIds[];
    private int documentId;
    
    /**
     * Creates new form DocumentProgressUI
     */
    public DocumentProgressUI(int documentId) {
        initComponents();

        this.documentId = documentId;
        dao = DocumentsListUI.dao;
        getStages();
        panelCheckBoxes = (List<JCheckBox>[]) Array.newInstance(List.class, stages.size());
        stageContent = (List<DocumentStageContent>[]) Array.newInstance(List.class, stages.size());
        panels = new ArrayList<>();
        documentProgress = dao.getDocumentProgress(documentId);
        stageIds = new int[stages.size()];
        for (DocumentStage stage : stages) {
            JPanel panel = new JPanel();
            panels.add(panel);
            int tabNumber = panels.size()-1;
            int stageId = stage.getId();
            stageIds[tabNumber] = stageId;
            jTabbedPane1.addTab(stage.getName(), panel);
            stageContent[tabNumber] = dao.getStageContent(stageId);
            panelCheckBoxes[tabNumber] = new ArrayList<>();
            panel.setLayout(new GridLayout(stageContent[tabNumber].size(), 1));
            for (DocumentStageContent content : stageContent[tabNumber]) {
                JCheckBox checkBox = new JCheckBox("<html>" + content.getName() + "</html>");
                checkBox.setSelected(documentProgress.contains(content.getId()));
                panelCheckBoxes[tabNumber].add(checkBox);
                panel.add(checkBox);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButtonCancel = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Прогресс разработки НИР");
        setPreferredSize(new java.awt.Dimension(650, 500));

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSave.setText("Сохранить");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSave))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        Set<Integer> selectedSet = new HashSet<>();
        for (int i=0; i<stages.size(); i++) {
            for (int j=0; j<stageContent[i].size(); j++) {
                if (panelCheckBoxes[i].get(j).isSelected()) {
                    selectedSet.add(stageContent[i].get(j).getId());
                }
            }
        }
        Set<Integer> addedSelections = new HashSet<>(selectedSet);
        Set<Integer> removedSelections = new HashSet<>(documentProgress);
        addedSelections.removeAll(documentProgress);
        dao.addDocumentProgress(documentId, addedSelections);
        removedSelections.removeAll(selectedSet);
        dao.delDocumentProgress(documentId, removedSelections);
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void getStages() {
        stages = dao.getStages();
    }
}
